### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by sergeevabc** [indiscipline/ffmpeg-loudnorm-helper#3]
Windows 7 x64, ffmpeg-loudnorm-helper 0.2.0

Source: [in.wav.zip](https://github.com/indiscipline/ffmpeg-loudnorm-helper/files/14623057/in.wav.zip)

``` console
$ ffmpeg-lh.exe in.wav
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"input_tp\", expected struct Loudness", line: 1, column: 11)', src/main.rs:126:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by indiscipline** [comment]
ffmpeg's output format changed a bit at some point. Demonstrates well that the magic numbers are evil and each `unwrap` is a liability.

Fixed in the upcoming release.

PS: Sorry for the delay with the fix, stopped receiving mail notifications thanks to my mail provider's spam filtering.

**Comment by sergeevabc** [comment]
It works as expected now, thank you.

``` console
$ ffmpeg-lh.exe in.wav
-af loudnorm=linear=true:I=-18:LRA=12:TP=-1:measured_I=-19.35:measured_TP=-4.74:measured_LRA=2.80:measured_thresh=-31.08:offset=0.53:print_format=summary
```
